const defaultStyles = {
  width: 1000,
  height: 712,
  headerHeight: 80,
  footerHeight: 30,
  fontSize: 12,
  fontFamily: "Arial, sans-serif",
  backgroundColor: "#f5f5ff",
  borderColor: "#1a3987",
  fontColor: "#1a3987",
  contentFontColor: "#333",
  highlightColor: "#d7e3fe",
  sectionColor: "#ffffff",
  padding: 10,
  cornerRadius: 10,
  circleRadius: 14,
  lineSize: 1,
  shadowColor: "rgba(0, 0, 0, 0.2)",
  stickyNoteSize: 80,
  stickyNoteSpacing: 10,
  stickyNoteCornerRadius: 1,
  maxLineWidth: 70,
  stickyNoteColor: "#fff399",
  stickyNoteBorderColor: "#fff399",
  defaultLocale: "en",
};

module.exports = defaultStyles;
